import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Explicit sidebars mirroring the former docs/fern/docs.yml navigation.
// `docsSidebar` is the main documentation tree (Overview -> ... ->
// CLI/environment reference), shown for the "Docs" navbar tab.
// `contributingSidebar` is a separate, smaller tree scoped to only the
// contributing-related pages, shown for the "Contributing" navbar tab, so
// neither tab's sidebar bleeds into the other's content. Kept hand-written
// (rather than autogenerated) so the order and grouping match the original
// Fern site exactly, including the "Architecture" section that mixes
// generated pages with canonical repo docs that live outside
// docs/docusaurus/docs (see scripts/sync-external-docs.mjs). The landing
// page itself is a standalone page (src/pages/index.mdx), not part of
// either sidebar, so it renders without the doc sidebar/TOC columns.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'quickstart',
    'installation',
    'upgrade',
    'migration',
    {
      type: 'category',
      label: 'User Guide',
      collapsed: false,
      items: [
        'user-guide/model-market',
        'user-guide/deployments',
        'user-guide/evaluation',
        'user-guide/simulation',
        'user-guide/model-services',
        'user-guide/clusters',
        'user-guide/storage',
        'user-guide/model-cache',
        'user-guide/external-providers',
        'user-guide/observability',
        'user-guide/lens-assistant',
        'user-guide/administration',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/bootstrap-and-deploy',
        'tutorials/evaluate-a-deployment',
        'tutorials/publish-a-model-service',
      ],
    },
    'integrations',
    'mcp',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/index',
        'architecture/agentic-deployment',
        'architecture/agentic-planning-evidence',
      ],
    },
    'troubleshooting',
    'faq',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/index',
        {
          type: 'category',
          label: 'Modules',
          items: [
            'api-reference/modules/model-market',
            'api-reference/modules/deployments',
            'api-reference/modules/evaluation',
            'api-reference/modules/simulation',
            'api-reference/modules/model-services',
            'api-reference/modules/clusters',
            'api-reference/modules/storage',
            'api-reference/modules/model-cache',
            'api-reference/modules/external-providers',
            'api-reference/modules/observability',
            'api-reference/modules/lens-assistant',
            'api-reference/modules/administration',
          ],
        },
      ],
    },
    'cli-reference',
    'environment-variables',
  ],
  contributingSidebar: ['resources/contributing', 'resources/add-new-hardware'],
};

export default sidebars;
